"""initial_schema

Revision ID: 151b6badb61e
Revises: 
Create Date: 2026-02-07 12:32:35.030025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151b6badb61e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_api_cache'))
    )
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_cache_expires_at'), ['expires_at'], unique=False)

    op.create_table('bot_configurations',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_bot_configurations'))
    )
    op.create_table('pending_verifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('captcha_answer', sa.String(length=16), nullable=True),
    sa.Column('scheduler_job_id', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_verifications'))
    )
    op.create_table('server_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('server_type', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('webhook_token', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tos', sa.String(length=4096), nullable=True),
    sa.Column('notify_topic_id', sa.BigInteger(), nullable=True),
    sa.Column('registration_mode', sa.String(length=32), server_default=sa.text("'default'"), nullable=False),
    sa.Column('registration_count_limit', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('registration_time_limit', sa.String(length=32), server_default=sa.text("'0'"), nullable=False),
    sa.Column('registration_expiry_days', sa.Integer(), server_default=sa.text('(30)'), nullable=False),
    sa.Column('registration_external_url', sa.String(length=1024), nullable=True),
    sa.Column('registration_external_parser', sa.String(length=1024), nullable=True),
    sa.Column('code_expiry_days', sa.Integer(), server_default=sa.text('(30)'), nullable=False),
    sa.Column('nsfw_enabled', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('nsfw_library_ids', sa.String(length=1024), server_default=sa.text("('')"), nullable=False),
    sa.Column('nsfw_sub_library_ids', sa.String(length=2048), server_default=sa.text("('')"), nullable=False),
    sa.Column('allow_subtitle_upload', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('path_mappings', sa.String(length=1024), nullable=True),
    sa.Column('request_notify_topic_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_instances')),
    sa.UniqueConstraint('name', name=op.f('uq_server_instances_name')),
    sa.UniqueConstraint('webhook_token', name=op.f('uq_server_instances_webhook_token'))
    )
    op.create_table('telegram_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('checkin_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('warning_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_checkin', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_users'))
    )
    op.create_table('active_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_instances.id'], name=op.f('fk_active_codes_server_id_server_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_active_codes'))
    )
    with op.batch_alter_table('active_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_codes_code'), ['code'], unique=True)

    op.create_table('media_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=64), nullable=False),
    sa.Column('media_name', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['telegram_users.id'], name=op.f('fk_media_user_id_telegram_users')),
    sa.ForeignKeyConstraint(['server_id'], ['server_instances.id'], name=op.f('fk_media_user_server_id_server_instances')),
    sa.PrimaryKeyConstraint('id', 'server_id', name=op.f('pk_media_user')),
    sa.UniqueConstraint('server_id', 'media_id', name='uq_server_media_id')
    )
    with op.batch_alter_table('media_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_user_media_id'), ['media_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_user_media_id'))

    op.drop_table('media_user')
    with op.batch_alter_table('active_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_codes_code'))

    op.drop_table('active_codes')
    op.drop_table('telegram_users')
    op.drop_table('server_instances')
    op.drop_table('pending_verifications')
    op.drop_table('bot_configurations')
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_cache_expires_at'))

    op.drop_table('api_cache')
    # ### end Alembic commands ###
