"""create library_bindings table

Revision ID: 530132ee9465
Revises: b0514ca045d1
Create Date: 2026-02-26 11:50:26.965515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530132ee9465'
down_revision: Union[str, Sequence[str], None] = 'b0514ca045d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('library_name', sa.String(length=128), nullable=False),
    sa.Column('arr_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('quality_profile_id', sa.Integer(), nullable=False),
    sa.Column('root_folder', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['arr_id'], ['server_instances.id'], name=op.f('fk_library_bindings_arr_id_server_instances')),
    sa.ForeignKeyConstraint(['media_id'], ['server_instances.id'], name=op.f('fk_library_bindings_media_id_server_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_bindings')),
    sa.UniqueConstraint('media_id', 'library_name', name='uq_media_library')
    )

    # --- 数据迁移：将 bot_configurations 中的 binding: 条目迁移到新表 ---
    import json

    conn = op.get_bind()

    # 查找第一个 Emby/Jellyfin 服务器作为 media_id（旧数据没有此字段）
    media_server_row = conn.execute(
        sa.text("SELECT id FROM server_instances WHERE server_type IN ('emby', 'jellyfin') LIMIT 1")
    ).fetchone()

    if not media_server_row:
        # 没有媒体服务器则跳过数据迁移（仅清理旧条目）
        conn.execute(sa.text("DELETE FROM bot_configurations WHERE key LIKE 'binding:%'"))
        return

    default_media_id = media_server_row[0]

    rows = conn.execute(
        sa.text("SELECT key, value FROM bot_configurations WHERE key LIKE 'binding:%'")
    ).fetchall()

    library_bindings = sa.table('library_bindings',
        sa.column('library_name', sa.String),
        sa.column('arr_id', sa.Integer),
        sa.column('media_id', sa.Integer),
        sa.column('quality_profile_id', sa.Integer),
        sa.column('root_folder', sa.String),
    )

    for row in rows:
        library_name = row[0].replace('binding:', '', 1)
        try:
            data = json.loads(row[1])
        except json.JSONDecodeError:
            continue

        arr_id = data.get('server_id')
        quality_profile_id = data.get('quality_profile_id')
        root_folder = data.get('root_folder')

        # 所有字段均为 NOT NULL，只迁移完整的绑定
        if arr_id and quality_profile_id and root_folder:
            op.execute(
                library_bindings.insert().values(
                    library_name=library_name,
                    arr_id=arr_id,
                    media_id=default_media_id,
                    quality_profile_id=quality_profile_id,
                    root_folder=root_folder,
                )
            )

    # 清除旧的 binding: 条目
    conn.execute(sa.text("DELETE FROM bot_configurations WHERE key LIKE 'binding:%'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_bindings')
    # ### end Alembic commands ###
