"""make active_codes server_id non-nullable

Revision ID: a66f6c77f8ba
Revises: 530132ee9465
Create Date: 2026-02-27 12:05:43.462574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66f6c77f8ba'
down_revision: Union[str, Sequence[str], None] = '530132ee9465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_codes', schema=None) as batch_op:
        batch_op.alter_column('server_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_codes', schema=None) as batch_op:
        batch_op.alter_column('server_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
