"""add allow_request to server_instances

Revision ID: b0514ca045d1
Revises: 151b6badb61e
Create Date: 2026-02-23 09:34:29.612371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0514ca045d1'
down_revision: Union[str, Sequence[str], None] = '151b6badb61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_request', sa.Boolean(), server_default=sa.text('(true)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_instances', schema=None) as batch_op:
        batch_op.drop_column('allow_request')

    # ### end Alembic commands ###
