"""add cascade delete to server foreign keys

Revision ID: ed544a07e347
Revises: a66f6c77f8ba
Create Date: 2026-02-27 12:49:34.670994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed544a07e347'
down_revision: Union[str, Sequence[str], None] = 'a66f6c77f8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_codes', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_active_codes_server_id_server_instances'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_active_codes_server_id_server_instances'), 'server_instances', ['server_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('library_bindings', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_library_bindings_arr_id_server_instances'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_library_bindings_media_id_server_instances'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_library_bindings_arr_id_server_instances'), 'server_instances', ['arr_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_library_bindings_media_id_server_instances'), 'server_instances', ['media_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('media_user', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_media_user_server_id_server_instances'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_media_user_server_id_server_instances'), 'server_instances', ['server_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_user', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_media_user_server_id_server_instances'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_media_user_server_id_server_instances'), 'server_instances', ['server_id'], ['id'])

    with op.batch_alter_table('library_bindings', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_library_bindings_media_id_server_instances'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_library_bindings_arr_id_server_instances'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_library_bindings_media_id_server_instances'), 'server_instances', ['media_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_library_bindings_arr_id_server_instances'), 'server_instances', ['arr_id'], ['id'])

    with op.batch_alter_table('active_codes', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_active_codes_server_id_server_instances'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_active_codes_server_id_server_instances'), 'server_instances', ['server_id'], ['id'])

    # ### end Alembic commands ###
